### ISSUE TITLE
AssPr is lower for all SOTA in Table 3 of the paper

### ISSUE THREAD

**Issue by rambleramble** [dendorferpatrick/QuoVadis#2]
Hi there, great work, thank you!

For Table 3 of the paper, seems the AssPr has been worse for all SOTA and both MOT17/20.  
Is there a reason of that, or any discussion related to this trend?

Thank you in advance!

**Comment by dendorferpatrick** [comment]
Sure, QuoVadis is a technique used to reduce identity switches, which occur when a tracking algorithm loses the gt track of an object and incorrectly associates it with a different object id. However, when QuoVadis is applied, it can lead to an increase in identity transfers, that is an association of the same tracking id with two different gt tracks. The reason for this is that QuoVadis focuses on reducing identity switches. However, the wrong re-association of tracks that were previously occluded can result in both an identity switch and an identity transfer (decreasing AssPr). It's important to note that QuoVadis can only associate lost tracks, it can't resolve previous identity transfers from the baseline tracker. Therefore, the AssPr (Identity Transfer) will always be larger or equal to the baseline performance.
I hope this answers your question. If not, let me know:)

**Comment by rambleramble** [comment]
Thank you foe the explanation
